# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: pretty-format-json
        args: [--autofix, --indent=4, --no-ensure-ascii]
-   repo: https://github.com/PyCQA/isort.git
    rev: 5.5.2
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black.git
    rev: 20.8b1
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.8.3
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-printf-formatting, flake8-comprehensions, flake8-commas, flake8-bugbear, pep8-naming]
        args: [--append-config=./.flake8]
        language_version: python3.8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.782'
    hooks:
    -   id: mypy
        args: [--config-file=./.mypy.ini]
        language_version: python3.8
-   repo: local
    hooks:
    -   id: unittest
        name: unittest
        entry: env PIPENV_IGNORE_VIRTUALENVS=1 pipenv run coverage run ./test_harness.py --text --test-level 'pre-commit'
        language: python
        always_run: True
        exclude: '^.*$'
